config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'captcha/index'
  # get 'captcha/solve'
  get 'meetings/index'
  get 'meetings/create'
  post 'meetings/create'
  post 'vk_admin/invite_user_friends'
  post 'vk_admin/create_captcha_objects'
  get 'meetings/invite'
  get 'polls/create'
  get 'polls/new'
  get 'polls/index'
  get 'invites/index'
  get 'invites/send_invite'
  get 'invites/create_invite'
  post 'send_invite/:user_id', to: 'invites#send_invite', as: :send_invite


  root 'welcome#index'

  get 'post/index'
  default_url_options host: 'theboosters.ru'
  get 'post/new'
  get 'post/show'
  get 'post/edit'
  get 'post/delete/:id', to: 'post#delete', as: 'post_delete'
  get 'post/approve/:id', to: 'post#approve_post', as: 'post_approve'
  get 'post/count_likes/:id', to: 'post#count_likes', as: 'count_likes'
  post 'captcha/solve/:id', to: 'captcha#solve', as: 'captcha_solve'
  get 'post/update_status/:id', to: 'post#update_status', as: 'post_status_update'
  get 'lk/index'
  get 'lk/vk'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'vk_admin/like_post'
  get 'vk_admin/follow_group'
  post 'vk_admin/make_like'
  post 'vk_admin/follow_group'
  post 'vk_admin/unfollow_group'
  post 'vk_admin/post_comment'
  get 'vk_admin/new_users_list'
  get 'vk_admin/new_posts_list'
  get 'vk_admin/preview_link'
  post 'vk_admin/preview_link'
  get 'welcome/index'
  get 'welcome/registered'
  get 'vk_admin/approve_user', to: 'vk_admin#approve_user'
  get 'vk_admin/invite_user/:user_id', to: 'vk_admin#invite_user', as: :invite_user

  # resources :post
  post '/post/new', to: 'post#new'
  get '/post/create', to: 'post#create'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: %i[get patch], :as => :finish_signup
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  before_action :new, only: [:index, :create]

  def new
    @meeting = Vcommunity.new
    @meeting.community_type = 'event'
  end

  def index
    @meetings =  Vcommunity.where(user: current_user, community_type: 'event')
  end

  def create
    current_user.vcommunities << Vcommunity.find_or_create_by_addr(current_user, params['meeting']['address'])
  end

  def invite
  end

  private

  def meeting_params
    accessible = %i[name address]
    params.require(:meeting).permit(accessible)
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_create_meeting.html.erb
<!--<div class="row justify-content-md-center">-->
<%= form_for @meeting, url: meetings_create_path, html: {method: :post, :class => "form-horizontal center"} do |f| %>
  <%#= f.label :name %>
  <!--    <%#= f.text_field :name %><br/>-->
  <div class="form-group row">
    <div class="col-md-1">
      <%= f.label "Тема:", class: "control-label h5" %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= f.label "Ссылка:", class: "control-label h5" %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="col-md-1">
      <%= f.submit "Создать", class: "btn btn-default btn-primary" %>
    </div>
  </div>
<% end %>


app/views/meetings/create.html.erb
<h1>Meetings#create</h1>
<p>Find me in app/views/meetings/create.html.erb</p>

app/views/meetings/index.html.erb
<h1>Meetings#index</h1>
<p>Find me in app/views/meetings/index.html.erb</p>


<%#= form_with model: @meeting, class: "nifty_form" do |f| %>
<%= form_for(@meeting, :as => 'meeting', :url => meetings_create_path, :html => {role: 'form'}) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :address %>
  <%= f.submit "Create" %>
<% end %>

<!--t.string "name"-->
<!--t.string "address"-->
<!--t.datetime "created_at", null: false-->
<!--t.datetime "updated_at", null: false-->
<!--t.integer "vkid", default: 0-->
<!--t.integer "community_type", default: 0-->

app/views/meetings/invite.html.erb
<h1>Meetings#invite</h1>
<p>Find me in app/views/meetings/invite.html.erb</p>