config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'captcha/index'
  # get 'captcha/solve'
  get 'meetings/index'
  get 'meetings/create'
  post 'meetings/create'
  post 'vk_admin/invite_user_friends'
  post 'vk_admin/create_captcha_objects'
  get 'meetings/invite'
  get 'polls/create'
  get 'polls/new'
  get 'polls/index'
  get 'invites/index'
  get 'invites/send_invite'
  get 'invites/create_invite'
  post 'send_invite/:user_id', to: 'invites#send_invite', as: :send_invite


  root 'welcome#index'

  get 'post/index'
  default_url_options host: 'theboosters.ru'
  get 'post/new'
  get 'post/show'
  get 'post/edit'
  get 'post/delete/:id', to: 'post#delete', as: 'post_delete'
  get 'post/approve/:id', to: 'post#approve_post', as: 'post_approve'
  get 'post/count_likes/:id', to: 'post#count_likes', as: 'count_likes'
  post 'captcha/solve/:id', to: 'captcha#solve', as: 'captcha_solve'
  get 'post/update_status/:id', to: 'post#update_status', as: 'post_status_update'
  get 'lk/index'
  get 'lk/vk'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'vk_admin/like_post'
  get 'vk_admin/follow_group'
  post 'vk_admin/make_like'
  post 'vk_admin/follow_group'
  post 'vk_admin/unfollow_group'
  post 'vk_admin/post_comment'
  get 'vk_admin/new_users_list'
  get 'vk_admin/new_posts_list'
  get 'vk_admin/preview_link'
  post 'vk_admin/preview_link'
  get 'welcome/index'
  get 'welcome/registered'
  get 'vk_admin/approve_user', to: 'vk_admin#approve_user'
  get 'vk_admin/invite_user/:user_id', to: 'vk_admin#invite_user', as: :invite_user

  # resources :post
  post '/post/new', to: 'post#new'
  get '/post/create', to: 'post#create'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: %i[get patch], :as => :finish_signup
end

app/controllers/vk_admin_controller.rb
# frozen_string_literal: true

require 'cgi'
require 'open-uri'
class VkAdminController < ApplicationController
  before_action :check_vk_admin, only: %i[approve_post edit]
  before_action :get_users_and_groups_ids, only: %i[invite_user_friends]


  def like_post
    @users_count = User.all.count
  end

  def make_like
    if current_user.vk_admin?
      what_to_like = params[:q]
      users = User.all.shuffle
      users.each do |u|
        Thread.new do
          LikeVcPostJob.set(wait: rand(5..7).seconds).perform_later(u, what_to_like)
        end
      end
    end
    flash[:success] = 'Likes are on their way'
    redirect_to vk_admin_like_post_path
  end

  def post_comment
    if current_user.vk_admin?
      messages = %w[!!!! атлична-атлична годнота жир Спасибо!]
      what_to_like = params[:q].sub!('https://vk.com/wall', '')
      users = User.all.shuffle
      users.find_each do |u|
        Thread.new do
          PostCommentJob.set(wait: rand(5..720).seconds).perform_later(u, what_to_like, messages.sample)
        end
      end
      flash[:success] = 'Comments are on their way'
    end
    redirect_to vk_admin_like_post_path
  end

  def invite_user
    group_id =  Rails.application.credentials.production[:group][:group_id]
    user = User.find(params[:user_id])
    # InviteUserToGroupJob.set(wait: rand(5..10).seconds).perform_later(user, group_id, current_user.vk_offline_token)
    # response = user.invite_user_to_vcommunity(user.vkid, group_id, current_user&.vk_offline_token)

    # flash[:info] = response
    flash[:info] = 'not yet implemented'

    redirect_to vk_admin_new_users_list_path

  end

  def follow_group
    if current_user.vk_admin?
      User.all.shuffle.find_each do |u|
        Thread.new do
          FollowVcommunityJob.set(wait: rand(5..720).seconds).perform_later(u, params[:q])
        end
      end
    end
    flash[:success] = 'The follow job has been started'
    redirect_to vk_admin_like_post_path
  end

  def create_captcha_objects
    RequestResponse.find_each do |rr|
      if rr.captcha.nil? && !rr.response.to_s.blank?
        if rr.response.is_a?(Hash) #Проверка на тип
          if rr.response.dig('error', 'error_code') == 14
            captcha = Captcha.new
            captcha.request_params = rr.response
            captcha.captcha_sid = rr.response.dig('error', 'captcha_sid')
            captcha.captcha_img = rr.response.dig('error', 'captcha_img')
            #TODO обработка сетевых ошибок
            c_img = open(captcha.captcha_img)
            # c_img = captcha.remove_background(captcha.captcha_img)
            captcha.image.attach(io: c_img, filename: captcha.captcha_sid)
            captcha.request_response = rr
            captcha.save!
          end
        end
      end
    end
    flash[:success] = 'The fill_out_captchajob has been started'
    redirect_to vk_admin_like_post_path
  end

  def invite_user_friends
    if current_user.vk_admin?
      Thread.new do
        User.all.shuffle.each do |u|
          get_friends_params = Hash.new(0)
          get_friends_params['order'] = 'random'
          get_friends_params['access_token'] = u.vk_offline_token
          get_friends_params['count'] = 3000
          get_friends_params['fields'] = 'nickname, city, status'
          get_friends_params['usr'] = u
          get_friends_params['user_id'] = u.vkid

          result = RequestResponse.make_request(:friends_get, get_friends_params)
          result = JSON.parse(result) unless result.nil?
          @friends = result.dig('response', 'items')
          unless @friends.nil?
            @friends.each_with_index do |f, i|
              if @all_users.include? f['id']
                @friends.delete_at(i)
                next
              end
              @all_vcommunities.each do |vcommunity|
                #TODO Колоссальная загрузка БД
                # Оптимизировать в первую очередь
                unless Invite.find_by_group_id_and_invited_id(vcommunity, f['id'])
                  invite = Invite.new
                  invite.user = u
                  invite.invited_id = f['id']
                  invite.group_id = vcommunity
                  invite.planned_time = DateTime.current
                  invite.save!
                end
              end

            end
            seconds_to_wait = rand(0..3)
            limit_reached = false
            user_invites = Invite.where(user: u, sent_at: nil, planned_time: DateTime.current.advance(:years => -1)...DateTime.current)
            user_invites.shuffle.each do |i|
              until limit_reached
                group_id = i.group_id
                user = i.user
                user_to_invite_id = i.invited_id
                sleep(seconds_to_wait)
                result = user.invite_user_to_vcommunity(u, user_to_invite_id, group_id, user.vk_offline_token)
                unless result.nil?
                  if JSON.parse(result).dig('error', 'error_code') == 14 #TODO парсинг капчи
                    i.update_attributes!('planned_time': DateTime.current.advance(:days => 1), 'request_params': result)
                  elsif JSON.parse(result).dig('error', 'error_code') == 15 #Пользователь запретил себя приглашать, удаляем все его инвайты
                    user_invites.each do |ui|
                      if ui.invited_id == i.invited_id
                        i.update_attributes!('sent_at': DateTime.current, 'request_params': result)
                      end
                    end
                  elsif not JSON.parse(result).dig('error', 'error_code').nil?
                    i.update_attributes!('planned_time': DateTime.current.advance(:days => 1), 'request_params': result)
                    limit_reached = true
                  else
                    i.update_attributes!('sent_at': DateTime.current, 'request_params': result)
                  end
                  sleep(rand(1..30).seconds)
                end
              end
            end
          end
        end
      end
      flash[:success] = 'The follow job has been started'
      redirect_to vk_admin_like_post_path
    end
  end

  def unfollow_group
    if current_user.vk_admin
      User.all.shuffle.each do |u|
        Thread.new do
          UnfollowVcommunityJob.set(wait: rand(5..720).seconds).perform_later(u, params[:q])
        end
      end
    end
    flash[:success] = 'The unfollow job has been started'
    redirect_to vk_admin_like_post_path
  end

# @return [Object]
  def approve_user
    us = User.find(params[:format])
    User.all.shuffle.each do |u|
      if u.isBoostersMember
        FollowVcommunityJob.set(wait: rand(5..720).seconds).perform_later(u, us.vcommunities.first)
        FollowVcommunityJob.set(wait: rand(5..720).seconds).perform_later(us, u.vcommunities.first)
      end
    end
    flash[:success] = 'The follow job has been started!'
    redirect_to vk_admin_like_post_path
  end

  def new_users_list
    @new_users = Role.find(1).users
  end

  def new_posts_list
    @new_posts = Post.where(status: 0)
  end

  def preview_link
    @group_html = URI.parse('https://vk.com/theboosters').read
    respond_to do |format|
      format.html {render 'vk_admin/group_preview'}
    end
  end

  private

  def get_users_and_groups_ids

    @all_users = User.all.shuffle.map(&:vkid)
    # @all_vcommunities = Vcommunity.where(community_type: 'event').map(&:vkid)
    @all_vcommunities = Vcommunity.all.shuffle.map(&:vkid)
  end

  def check_vk_admin
    true if current_user.vk_admin
  end

  def uuid
    'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'.gsub('x') do
      rand(16).to_s(16)
    end
  end

end

app/helpers/vk_admin_helper.rb
module VkAdminHelper
end

app/views/vk_admin/_comment_post.html.erb
<div class="row justify-content-md-center">
  <h2>Запостить комменты</h2>
</div>
<div class="row justify-content-md-center">
  <%= form_tag({controller: "vk_admin", action: "post_comment"}, method: "post") do %>
    <%= label_tag(:q, "URL:") %>
    <%= text_field_tag(:q, nil, placeholder: 'Например, https://vk.com/theboosters') %>
    <%= submit_tag("Comment!") %>
  <% end %>
</div>

app/views/vk_admin/_create_captcha_objects.erb
<div class="row justify-content-md-center">
  <h2>Создать объекты капчи</h2>
</div>
<div class="row justify-content-md-center">
  <%= form_tag({controller: "vk_admin", action: "create_captcha_objects"}, method: "post") do %>
    <%= submit_tag("Создать объекты капчи") %>
  <% end %>
</div>

app/views/vk_admin/_follow_group.html.erb
<div class="row justify-content-md-center">
  <h2>Вступить в группу</h2>
</div>
<div class="row justify-content-md-center">
  <%= form_tag({controller: "vk_admin", action: "follow_group"}, method: "post") do %>
    <%= label_tag(:q, "URL:") %>
    <%= text_field_tag(:q, nil, placeholder: 'Например, https://vk.com/theboosters') %>
    <%= submit_tag("Follow!") %>
  <% end %>
</div>
<div class="row justify-content-md-center">
  <h2>Отписаться от группы</h2>
</div>
<div class="row justify-content-md-center">
  <%= form_tag({controller: "vk_admin", action: "unfollow_group"}, method: "post") do %>
    <%= label_tag(:q, "URL:") %>
    <%= text_field_tag(:q, nil, placeholder: 'Например, https://vk.com/theboosters') %>
    <%= submit_tag("Leave!") %>
  <% end %>

</div>

app/views/vk_admin/_group_preview.js.erb
$('#results').html("<%= j (render 'group_preview.html') %>")

app/views/vk_admin/_invite_friends_to_group.html.erb
<div class="row justify-content-md-center">
  <h2>Пригласить друзей!</h2>
</div>
<div class="row justify-content-md-center">
  <%= form_tag({controller: "vk_admin", action: "invite_user_friends"}, method: "post") do %>
    <%#= label_tag(:q, "URL:") %>
    <%#= text_field_tag(:q, nil, placeholder: 'Например, https://vk.com/theboosters') %>
    <%= submit_tag("Пригласить всех друзей всех юзеров во все группы") %>
  <% end %>
</div>

app/views/vk_admin/group_preview.html.erb
<div id="group">
</div>
<script>
    $("#group")
        .html('<object data="<%= @group_html.html_safe %>"/>');
</script>

app/views/vk_admin/like_post.html.erb
<% if current_user&.vk_admin? %>
  <div class="row justify-content-md-center">
    <div class="h2">Панель администратора ВК</div>
  </div>
  <div class="row justify-content-md-left">
    Total users: <%= @users_count %>
  </div>

  <div class="col-md-10 text-center">
    <div class="row justify-content-md-center">
      <h2>Лайкнуть пост</h2>
    </div>
    <div class="row justify-content-md-center">

      <%= form_tag({controller: "vk_admin", action: "make_like"}, method: "POST") do %>
        <%= label_tag(:q, "URL:") %>
        <%= text_field_tag(:q, nil, placeholder: 'Например, https://vk.com/wall-72495085_870406') %>
        <%= submit_tag("Like!") %>
      <% end %>
    </div>
    <%= render 'vk_admin/follow_group' %>
    <%= render 'vk_admin/comment_post' %>
    <%= render 'vk_admin/create_captcha_objects' %>
    <%= render 'vk_admin/invite_friends_to_group' %>
  </div>

<% else %>
  <p> Извините, недостаточно прав для просмотра этой страницы :(</p>
<% end %>
</div>

app/views/vk_admin/new_posts_list.html.erb
<div class="col-lg-8">
  <% if @new_posts.size == 0 %>
    <h3>Нет необработанных постов!</h3>
  <% else %>
    <div class="row">
      <h3>Новые посты:</h3>
    </div>
    <table class="table table-bordered">
      <thead>
      <tr>
        <!--      <th scope="col"></th>-->
        <th scope="col">Автор</th>
        <th scope="col">Ссылка</th>
        <th scope="co1">Одобрить</th>
        <th scope="co1">Удалить</th>
        <!--      <th scope="co1">Подписка</th>-->
        <!--      <th scope="co1"></th>-->
      </tr>
      </thead>
      <tbody>
      <% @new_posts.each do |p| %>
        <div class="row text-center">
          <tr>
            <td>  <%= p.user.name %> </td>
            <td>
              <%= link_to p.name, p.address %>
            </td>
            <td><%= link_to '<button class="btn btn-small btn-success">Одобрить</button>'.html_safe, post_approve_path(p) %></td>
            <td><%= link_to '<button class="btn btn-small btn-danger">Удалить</button>'.html_safe, post_delete_path(p) unless p.status == 1 %></td>
          </tr>
      <% end %>
      </div>
      </tbody>
    </table>
  <% end %>
</div>
<!--<div id="pages_content">-->
<%#= render vk_admin_preview_link_path %>
<!--</div>-->

<!--<script>-->
<!--    $("#mydiv")-->
<!--        .html('<object data="<%= vk_admin_preview_link_path %>"/>');-->
<!--</script>-->

app/views/vk_admin/new_users_list.html.erb
<div class="col-lg-8">
  <div class="row">
    <h3>Новые пользователи:</h3>
  </div>
  <table class="table table-bordered">
    <thead>
    <tr>
      <!--      <th scope="col"></th>-->
      <th colspan="2" scope="col">Имя</th>
      <th colspan="2" scope="col">Группы</th>
      <th scope="co1">в бустерс?</th>
      <th scope="co1">Подписка</th>
      <th scope="co1"></th>
    </tr>
    </thead>
    <tbody>
    <% @new_users.each do |u| %>
      <div class="row text-center">
        <tr>
          <td colspan="2">  <%= u.name %> </td>
          <td colspan="2">
            <% u.vcommunities.all.each do |v| %>
              <%= link_to v.name, v.address %>
            <% end %>
          </td>
          <td class="text-center"> <%= check_box "inBoosters", "inBoosters", {:checked => u.isBoostersMember, :disabled => true} %></td>
          <td class="text-center"> <%= check_box "subrscr", "subrscr", {:checked => false, :disabled => true} %></td>
          <% if u.isBoostersMember %>
            <td><%= link_to "<button>Подтвердить</button>".html_safe, vk_admin_approve_user_path(u) %></td>
          <% else %>
            <td><%= link_to "<button>Пригласить</button>".html_safe, invite_user_path(u) %></td>
          <% end %>
        </tr>
    <% end %>
    </div>
    </tbody>
  </table>
  <%# end %>
</div>
<!--<div id="pages_content">-->
<%#= render vk_admin_preview_link_path %>
<!--</div>-->
<div class="row">
  <div class="col-lg-12">
    <div id="mydiv"></div>
  </div>
</div>
<!--<script>-->
<!--    $("#mydiv")-->
<!--        .html('<object data="<%= vk_admin_preview_link_path %>"/>');-->
<!--</script>-->