config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'captcha/index'
  # get 'captcha/solve'
  get 'meetings/index'
  get 'meetings/create'
  post 'meetings/create'
  post 'vk_admin/invite_user_friends'
  post 'vk_admin/create_captcha_objects'
  get 'meetings/invite'
  get 'polls/create'
  get 'polls/new'
  get 'polls/index'
  get 'invites/index'
  get 'invites/send_invite'
  get 'invites/create_invite'
  post 'send_invite/:user_id', to: 'invites#send_invite', as: :send_invite


  root 'welcome#index'

  get 'post/index'
  default_url_options host: 'theboosters.ru'
  get 'post/new'
  get 'post/show'
  get 'post/edit'
  get 'post/delete/:id', to: 'post#delete', as: 'post_delete'
  get 'post/approve/:id', to: 'post#approve_post', as: 'post_approve'
  get 'post/count_likes/:id', to: 'post#count_likes', as: 'count_likes'
  post 'captcha/solve/:id', to: 'captcha#solve', as: 'captcha_solve'
  get 'post/update_status/:id', to: 'post#update_status', as: 'post_status_update'
  get 'lk/index'
  get 'lk/vk'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'vk_admin/like_post'
  get 'vk_admin/follow_group'
  post 'vk_admin/make_like'
  post 'vk_admin/follow_group'
  post 'vk_admin/unfollow_group'
  post 'vk_admin/post_comment'
  get 'vk_admin/new_users_list'
  get 'vk_admin/new_posts_list'
  get 'vk_admin/preview_link'
  post 'vk_admin/preview_link'
  get 'welcome/index'
  get 'welcome/registered'
  get 'vk_admin/approve_user', to: 'vk_admin#approve_user'
  get 'vk_admin/invite_user/:user_id', to: 'vk_admin#invite_user', as: :invite_user

  # resources :post
  post '/post/new', to: 'post#new'
  get '/post/create', to: 'post#create'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: %i[get patch], :as => :finish_signup
end

app/models/post.rb
# frozen_string_literal: true
require "awesome_print"
class Post < ApplicationRecord
  validates :name, presence: {message: "Укажите тему поста!"}
  validates :address, presence: {message: "Укажите ссылку на пост!"}
  validates :address, post_url: {message: "Правильная выглядит так: 'https://vk.com/wall*******_**' !"}
  validates :address, uniqueness: {message: "Пост уже был обработан ранее!", case_sensitive: false}
  belongs_to :user
  attr_accessor :likes
  attr_accessor :comments

  def self.update_status(post, status)
    post.status = status
  end

  def self.get_likes(url, a_token = Rails.application.credentials.production[:group][:a_token])
    owner_item = url.split('wall').last.split('_')
    get_likes_params = Hash.new(0)
    get_likes_params['type'] = 'post'
    get_likes_params['owner_id'] = owner_item[0].to_i
    get_likes_params['item_id'] = owner_item[1].to_i
    get_likes_params['filter'] = 'likes'
    get_likes_params['friends_only'] = '0'
    get_likes_params['v'] = 5.92
    get_likes_params['access_token'] = a_token
    result = URI.parse("https://api.vk.com/method/likes.getList?#{get_likes_params.to_query}").read
    ap result
    if JSON.parse(result)['response']
      count = JSON.parse(result)['response']['count']
      if count.nil?
        return 'Ошибка'
      else
        return count
      end
    end
    # JSON.parse(result)['error']['error_msg'].to_s
  end

  def self.get_comments(url, a_token =  Rails.application.credentials.production[:group][:a_token])
    owner_item = url.split('wall').last.split('_')
    get_likes_params = Hash.new(0)
    p owner_item
    # get_likes_params['type'] = 'post'
    get_likes_params['owner_id'] = owner_item[0].to_i
    get_likes_params['post_id'] = owner_item[1].to_i
    get_likes_params['need_likes'] = true
    # get_likes_params['filter'] = 'likes'
    # get_likes_params['friends_only'] = '0'
    get_likes_params['thread_items_count'] = 0
    get_likes_params['v'] = 5.92
    get_likes_params['access_token'] = a_token
    result = URI.parse("https://api.vk.com/method/wall.getComments?#{get_likes_params.to_query}").read
    ap result, :indent => -2
    if JSON.parse(result)['response']
      count = JSON.parse(result)['response']['count']
      # //TODO пофиксить лайки
      # likes = JSON.parse(result)['response']['items']
      # likes = JSON.parse(result).dig(:response, :items, :likes, :count)
      # ap likes
      if count.nil?
        return 'Ошибка'
      else
        return count
        # return count, likes
      end
    end
    # JSON.parse(result)['error']['error_msg'].to_s
  end
end

app/controllers/post_controller.rb
# frozen_string_literal: true

class PostController < ApplicationController
  before_action :check_current_user # , only: %i[show edit destroy update_status count_likes approve_post get_post_comments index]
  before_action :set_post, only: %i[show edit destroy update_status count_likes approve_post get_post_comments]
  before_action :check_vk_admin, only: %i[approve_post edit]
  before_action :create, only: %i[index new]

  def index
    @user_posts = current_user.posts if current_user
    @user_posts = @user_posts.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def new
    @new_post = Post.new(post_params)
    if @new_post.address.split('wall').first != 'https://vk.com/'
      flash[:danger] = "Неверная ссылка! \nПравильная выглядит так: 'https://vk.com/wall*******_**' "
    else
      current_user.posts << @new_post
      if current_user.save
        flash[:success] = "Пост был успешно добавлен и ожидает модерации.\nЭто может занять какое-то время."
        PostMailer.with(user: current_user&.name, post: @new_post).new_post_email.deliver_now
      else
        mes = "Не удалось разместить пост: \n"
        @new_post.errors.full_messages.each do |message|
          p message
          mes = mes + message + "\n"
        end
        flash[:danger] = mes
      end
    end
    redirect_to post_index_path
  end

  def show;
  end

  def edit
    flash[:danger] = 'Вы не можете редактировать посты'
    redirect_to post_index_path
  end

  def delete
    @post = Post.find(params[:id])
    if current_user.posts.include? @post
      @post.destroy
      flash[:success] = 'Пост был удален'
    else
      flash[:danger] = 'Вы не можете удалить этот  пост'
    end
    redirect_to post_index_path
  end

  def update_status
    @post.update_attributes(status: 0)
    redirect_to controller: :vk_admin, action: :new_posts_list
  end

  def count_likes
    if @post
      address = @post.address
      @post.likes_count = Post.get_likes(address, current_user.vk_offline_token)
      @post.comments_count = Post.get_comments(address, current_user.vk_offline_token)
      respond_to do |format|
        format.js {render partial: 'post/result'}
      end
    else
      flash[:danger] = 'You have entered an incorrect symbol'
      redirect_to post_index_path
    end
  end

  def approve_post
    User.all.shuffle.each do |u|
      LikeVcPostJob.set(wait: rand(5..720).seconds).perform_later(u, @post.address)
    end
    @post.update_attributes(status: 3)
    flash[:success] = 'Процесс запущен и продлится не более двух часов'
    redirect_to vk_admin_new_posts_list_path
  end

  private

  def post_params
    accessible = %i[name address]
    params.require(:post).permit(accessible)
  end

  def update
    @post = Post.find(params[:id])
    authorize @post
    if @post.update(post_params)
      redirect_to @post
    else
      render :index
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def check_vk_admin
    true if current_user.vk_admin
  end

  def check_current_user
    if current_user.nil? || current_user.isBoostersMember == false
      flash[:danger] = 'У вас пока нет доступа к этой странице :('
      redirect_to root_path
    end
  end

  def create
    @new_post = Post.new
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/post/_create_post.html.erb
<!--<div class="row justify-content-md-center">-->
<%= form_for @new_post, url: post_new_path, html: {method: :post, :class => "form-horizontal center"} do |f| %>
  <%#= f.label :name %>
  <!--    <%#= f.text_field :name %><br/>-->
  <div class="form-group row">
    <div class="col-md-1">
      <%= f.label "Тема:", class: "control-label h5" %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= f.label "Ссылка:", class: "control-label h5" %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="col-md-1">
      <%= f.submit "Создать", class: "btn btn-default btn-primary" %>
    </div>
  </div>
<% end %>

app/views/post/_result.html.erb
<% if @post %>
  <div class="well results-block border1">
    <hi><strong>Статистика для <%= link_to @post.name, @post.address %> </strong></hi>

    <p><strong>Лайки: </strong> <%= @post.likes_count %>
      <strong>Комменты: </strong> <%= @post.comments_count %>
    </p>

  </div>
<% end %>

app/views/post/_result.js.erb
$('#results').html("<%= j (render 'post/result.html') %>")

app/views/post/create.html.erb
<div class="row justify-content-md-center">
  <%= form_for @new_post, url: post_new_path, html: {method: :post} do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br/>
    <%= f.label :address %>
    <%= f.text_field :address %><br/>
    <%= f.submit %>
  <% end %>
</div>

app/views/post/delete.html.erb
<h1>Post#delete</h1>
<p>Find me in app/views/post/delete.html.erb</p>

app/views/post/edit.html.erb
<h1>Post#edit</h1>
<p>Find me in app/views/post/edit.html.erb</p>

app/views/post/index.html.erb
<h4>Продвинуть новый пост:</h4>
<div class="col-md-9">
  <%= render 'create_post' %>
</div>
<h4>Продвигаемые посты:</h4>

<% if @user_posts.size == 0 %>
  <b>У вас пока нет продвигаемых постов</b>
<% else %>

  <div class="row">
    <b> Всего постов: <%= @user_posts.size %> </b>
  </div>
  <div id="results">
    <%= render 'result' %>
  </div>
  <table class="table table-bordered text-center">
    <thead>
    <tr>
      <th colspan="2" scope="col">Тема</th>
      <th colspan="2" scope="col">Ссылка</th>
      <th colspan="2" scope="col">Статус</th>
      <th colspan="1" scope="col">Статистика</th>
      <th colspan="2" scope="col">Удалить</th>
    </tr>
    <div class="digg_pagination">
      <%= will_paginate @user_posts %>
    </div>
    </thead>
    <tbody>
    <% @user_posts.each do |p| %>
      <div class="row text-center">
        <tr>
          <td colspan="2">  <%= p.name %> </td>
          <td colspan="2">  <%= link_to p.name, p.address %> </td>
          <td colspan="2"><%= case p.status
                              when 0
                                'На согласовании'
                              when 1
                                'Обрабатывается'
                              when 2
                                'Отказ'
                              when 3
                                'Обработан'
                              else
                                "Неизвестный статус: #{p.status}"
                              end %>
          </td>
          <td colspan="1">
            <div id="stock-lookup_" #{p.status} class="text-center">
              <%= form_tag count_likes_path(p.id), remote: true, method: :get,
                           id: "stock-lookup-form" do %>
                <div class="text-center">
                  <%= button_tag(type: :submit, class: "btn btn-small") do %>
                    <i class="fa fa-refresh"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
          </td>
          <td colspan="2">
            <div class="text-center">
              <% if p.status == 0 || p.status == 3 %>
                <%= link_to '<button class="btn btn-small btn-danger"> <i class="fa fa-trash"></i></button>'.html_safe, post_delete_path(p) %>
                </div></td>
              <% else %>
                -
              <% end %>
              </tr>
      </div>
    <% end %>
<% end %>
</tbody>
</table>




app/views/post/new.html.erb
<h1>Post#new</h1>
<p>Find me in app/views/post/new.html.erb</p>

app/views/post/show.html.erb
<h1>Post#show</h1>
<p>Find me in app/views/post/show.html.erb</p>