config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'captcha/index'
  # get 'captcha/solve'
  get 'meetings/index'
  get 'meetings/create'
  post 'meetings/create'
  post 'vk_admin/invite_user_friends'
  post 'vk_admin/create_captcha_objects'
  get 'meetings/invite'
  get 'polls/create'
  get 'polls/new'
  get 'polls/index'
  get 'invites/index'
  get 'invites/send_invite'
  get 'invites/create_invite'
  post 'send_invite/:user_id', to: 'invites#send_invite', as: :send_invite


  root 'welcome#index'

  get 'post/index'
  default_url_options host: 'theboosters.ru'
  get 'post/new'
  get 'post/show'
  get 'post/edit'
  get 'post/delete/:id', to: 'post#delete', as: 'post_delete'
  get 'post/approve/:id', to: 'post#approve_post', as: 'post_approve'
  get 'post/count_likes/:id', to: 'post#count_likes', as: 'count_likes'
  post 'captcha/solve/:id', to: 'captcha#solve', as: 'captcha_solve'
  get 'post/update_status/:id', to: 'post#update_status', as: 'post_status_update'
  get 'lk/index'
  get 'lk/vk'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'vk_admin/like_post'
  get 'vk_admin/follow_group'
  post 'vk_admin/make_like'
  post 'vk_admin/follow_group'
  post 'vk_admin/unfollow_group'
  post 'vk_admin/post_comment'
  get 'vk_admin/new_users_list'
  get 'vk_admin/new_posts_list'
  get 'vk_admin/preview_link'
  post 'vk_admin/preview_link'
  get 'welcome/index'
  get 'welcome/registered'
  get 'vk_admin/approve_user', to: 'vk_admin#approve_user'
  get 'vk_admin/invite_user/:user_id', to: 'vk_admin#invite_user', as: :invite_user

  # resources :post
  post '/post/new', to: 'post#new'
  get '/post/create', to: 'post#create'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: %i[get patch], :as => :finish_signup
end

app/views/common/_footer.html.erb
<div class="v-offst-15">
  <footer id="footer" class="fixed-bottom footer">
  <span class="text-muted text-right right">
    <p class="text-right"> v. 0.0.41 от 09.05.19 </p>
  </span>
  </footer>
</div>

app/views/common/_navbar.html.erb
<!--<div class="wrapper"></div>-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'The Boosters', root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if current_user %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item">
          <%= link_to 'Мои посты', post_index_path, class: 'nav-link' %>
        </li>

        <!--        <li class="nav-item">-->
        <%#= link_to 'Мои приглашения', invites_index_path, class: 'nav-link' %>
        <!--        </li>-->

        <li class="nav-item">
          <%= link_to 'Мои встречи', meetings_index_path, class: 'nav-link' %>
        </li>
      </ul>

      <div class="btn-group">
        <button type="button" class="btn dropdown-toggle btn-dark" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
          Администрирование
        </button>
        <div class="dropdown-menu dropdown-menu-lg-right">
          <%= link_to 'Администрирование ВК', vk_admin_like_post_path, class: "dropdown-item" %>
          <%= link_to 'Список новичков', vk_admin_new_users_list_path, class: "dropdown-item" %>
          <%= link_to 'Модерация постов', vk_admin_new_posts_list_path, class: "dropdown-item" %>
          <% if current_user&.is_admin? %>
            <%= link_to 'Администрирование приложения', rails_admin_path, method: :get, class: "dropdown-item" %>
          <% end %>
        </div>
      </div>
      <div class="nav-item dropdown">
        <button type="button" class="btn dropdown-toggle btn-dark" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
          Профиль
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          <% if user_signed_in? %>
            <%= link_to 'Обновить токен', finish_signup_path(current_user), method: :get, class: "dropdown-item" %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%= link_to 'Решить капчи', captcha_index_path, method: :get, class: "dropdown-item" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</nav>